### ISSUE TITLE
Rebase of commits

### ISSUE THREAD

**Issue by lucasgomide** [fidelisrafael/nifty_services#12]
Before merged something, i'd like rebase all commits to keep history readable.
what you think?

@fidelisrafael @viniciuszago

**Comment by viniciuszago** [comment]
Maybe a PR can be larger, but if you keep in mind to have a rule like maximum of 3 commits for a PR would be great

**Comment by lucasgomide** [comment]
Yeap, for a simple PR don't make sense the rebase. But i agree with your rule. 3  commits for each PR would great !

**Comment by fidelisrafael** [comment]
Well, we can at least try this, readable history is always good
