### ISSUE TITLE
Move this README into Wiki Pages

### ISSUE THREAD

**Issue by viniciuszago** [fidelisrafael/nifty_services#29]
Hi Fidelis,

I spent some time reading all documentation and I think it is confuse sometimes, because there is too much information on the same page and I need to keep scrolling to find something I have read.

What do you think to move everything to Wiki pages and just let the summary on README?

**Comment by fidelisrafael** [comment]
Hi, you're right! That documentation is huge! I will start the migration to Wiki. Thanks for contributing.

**Comment by fidelisrafael** [comment]
@viniciuszago Thanks for your suggestion, I'm doing all migration in this PR: #32

**Comment by fidelisrafael** [comment]
Live: https://github.com/fidelisrafael/nifty_services/tree/doc_to_wiki

**Comment by viniciuszago** [comment]
Well done.
